class NoUserFoundException(Exception):
    pass

class UsernameAlreadyExistsException(Exception):
    pass
